find_package(PkgConfig REQUIRED)
pkg_search_module(nlohmann_json REQUIRED IMPORTED_TARGET nlohmann_json)
pkg_search_module(Vulkan REQUIRED IMPORTED_TARGET vulkan)
pkg_search_module(SPIRV-Headers REQUIRED IMPORTED_TARGET SPIRV-Headers)
pkg_search_module(Zstd REQUIRED IMPORTED_TARGET libzstd)
find_package(SDL2 REQUIRED)
find_package(PNG REQUIRED)
find_package(SQLite3 REQUIRED)
find_package(Freetype REQUIRED)
pkg_search_module(Harfbuzz REQUIRED IMPORTED_TARGET harfbuzz)
if(LINUX)
pkg_search_module(WaylandClient REQUIRED IMPORTED_TARGET wayland-client)
pkg_search_module(WaylandProtocols REQUIRED IMPORTED_TARGET wayland-protocols)
pkg_search_module(XkbCommon REQUIRED IMPORTED_TARGET xkbcommon)
endif()
