// this file is included multiple times with macros defined in various ways
// so all keys can be defined here once

K(_Unknown, Unknown, 0)
K(BackSpace, BackSpace, 0x08)
K(Tab, Tab, 0x09)
K(LineFeed, LineFeed, 0x0a)
K(Clear, Clear, 0x0b)
K(Return, Return, 0x0d)
K(Pause, Pause, 0x13)
K(ScrollLock, ScrollLock, 0x14)
K(SysReq, SysReq, 0x15)
K(Escape, Escape, 0x1b)
K(Insert, Insert, 0x1c)
K(Delete, Delete, 0x1d)
K(Space, Space, ' ') // 0x20
K(Comma, Comma, ',') // 0x2c
K(Hyphen, Hyphen, '-') // 0x2d
K(Period, Period, '.') // 0x2e
K(Slash, Slash, '/') // 0x2f
K(_0, 0, '0') // 0x30
K(_1, 1, '1')
K(_2, 2, '2')
K(_3, 3, '3')
K(_4, 4, '4')
K(_5, 5, '5')
K(_6, 6, '6')
K(_7, 7, '7')
K(_8, 8, '8')
K(_9, 9, '9') // 0x39
K(A, A, 'A') // 0x41
K(B, B, 'B')
K(C, C, 'C')
K(D, D, 'D')
K(E, E, 'E')
K(F, F, 'F')
K(G, G, 'G')
K(H, H, 'H')
K(I, I, 'I')
K(J, J, 'J')
K(K, K, 'K')
K(L, L, 'L')
K(M, M, 'M')
K(N, N, 'N')
K(O, O, 'O')
K(P, P, 'P')
K(Q, Q, 'Q')
K(R, R, 'R')
K(S, S, 'S')
K(T, T, 'T')
K(U, U, 'U')
K(V, V, 'V')
K(W, W, 'W')
K(X, X, 'X')
K(Y, Y, 'Y')
K(Z, Z, 'Z') // 0x5A
K(Home, Home, 0x60)
K(Left, Left, 0x61)
K(Up, Up, 0x62)
K(Right, Right, 0x63)
K(Down, Down, 0x64)
K(PageUp, PageUp, 0x65)
K(PageDown, PageDown, 0x66)
K(End, End, 0x67)
K(Begin, Begin, 0x68)
K(Grave, Grave, 0x7e)
K(NumLock, NumLock, 0x7f)
K(NumPadSpace, NumPadSpace, 0x80)
K(NumPadTab, NumPadTab, 0x89)
K(NumPadEnter, NumPadEnter, 0x8d)
K(NumPadF1, NumPadF1, 0x91)
K(NumPadF2, NumPadF2, 0x92)
K(NumPadF3, NumPadF3, 0x93)
K(NumPadF4, NumPadF4, 0x94)
K(NumPadHome, NumPadHome, 0x95)
K(NumPadLeft, NumPadLeft, 0x96)
K(NumPadUp, NumPadUp, 0x97)
K(NumPadRight, NumPadRight, 0x98)
K(NumPadDown, NumPadDown, 0x99)
K(NumPadPageUp, NumPadPageUp, 0x9a)
K(NumPadPageDown, NumPadPageDown, 0x9b)
K(NumPadEnd, NumPadEnd, 0x9c)
K(NumPadBegin, NumPadBegin, 0x9d)
K(NumPadInsert, NumPadInsert, 0x9e)
K(NumPadDelete, NumPadDelete, 0x9f)
K(NumPadEqual, NumPadEqual, 0xbd)
K(NumPadMultiply, NumPadMultiply, 0xaa)
K(NumPadAdd, NumPadAdd, 0xab)
K(NumPadSeparator, NumPadSeparator, 0xac)
K(NumPadSubtract, NumPadSubtract, 0xad)
K(NumPadDecimal, NumPadDecimal, 0xae)
K(NumPadDivide, NumPadDivide, 0xaf)
K(NumPad0, NumPad0, 0xb0)
K(NumPad1, NumPad1, 0xb1)
K(NumPad2, NumPad2, 0xb2)
K(NumPad3, NumPad3, 0xb3)
K(NumPad4, NumPad4, 0xb4)
K(NumPad5, NumPad5, 0xb5)
K(NumPad6, NumPad6, 0xb6)
K(NumPad7, NumPad7, 0xb7)
K(NumPad8, NumPad8, 0xb8)
K(NumPad9, NumPad9, 0xb9)
K(F1, F1, 0xbe)
K(F2, F2, 0xbf)
K(F3, F3, 0xc0)
K(F4, F4, 0xc1)
K(F5, F5, 0xc2)
K(F6, F6, 0xc3)
K(F7, F7, 0xc4)
K(F8, F8, 0xc5)
K(F9, F9, 0xc6)
K(F10, F10, 0xc7)
K(F11, F11, 0xc8)
K(F12, F12, 0xc9)
K(ShiftL, ShiftL, 0xe1)
K(ShiftR, ShiftR, 0xe2)
K(ControlL, ControlL, 0xe3)
K(ControlR, ControlR, 0xe4)
K(CapsLock, CapsLock, 0xe5)
K(AltL, AltL, 0xe9)
K(AltR, AltR, 0xea)
K(SuperL, SuperL, 0xeb)
K(SuperR, SuperR, 0xec)
K(Shift, Shift, 0xed)
K(Control, Control, 0xee)
K(Alt, Alt, 0xef)
